[build-system]
requires = [
    "setuptools >= 77.0.3",
    "pybind11",
]
build-backend = "setuptools.build_meta"

[project]
version = '0.0.1'
name = 'xmlwriter'
author='Paul Ross'
author_email='apaulross@gmail.com'
url='https://github.com/paulross/xmlwriter'
description='An XML/HTML/SVG writer project using pybind11'
dependencies = [
    "pybind11",
    "psutil",
    "pytest",
    "pytest-benchmark",
    "pytest-benchmark[histogram]",
    "Sphinx",
]
